{ lib }:

''
# ─────────────────────────────────────────────────────────────
# Powerlevel10k configuration (generated by Nix)
# ─────────────────────────────────────────────────────────────

typeset -g POWERLEVEL9K_MODE=nerdfont-complete

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  time
)

typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=3
typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=2
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=3
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=1

typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
''

